#!/usr/bin/env bash
# T3 devops — prove the release archives are bit-for-bit reproducible.
#
# Usage: scripts/release/linux-repro-check.sh <amd64|arm64> <evidence-dir>
#
# docs/release/artifact-verification.md tells a verifier to rebuild a commit and
# `diff` the checksums. That is a PRODUCT CLAIM, and until this script existed
# nothing tested it — the claim was asserted, never measured. This builds the
# frozen snapshot TWICE from an identical source tree inside one Linux container
# and compares the produced artifacts.
#
# The verdict is computed from the ARTIFACT DIGESTS ONLY (the four built
# binaries and the per-arch tarballs). Host-side staging mtimes are printed as
# diagnostic context but deliberately excluded from the verdict: the completions
# are regenerated by the before-hook every run, so their source mtime ALWAYS
# differs. The point of the archive `info.mtime` pinning in
# packaging/goreleaser/goreleaser.yaml is that this difference must not reach
# the tar headers. Including it in the verdict would make the gate permanently
# and falsely red.
set -euo pipefail
cd "$(dirname "$0")/../.."

ARCH="${1:?amd64|arm64}"
EVID="${2:?evidence dir}"
mkdir -p "$EVID"

# shellcheck disable=SC1091
. scripts/tools.env

case "$ARCH" in
  amd64|arm64) PLATFORM="--platform linux/$ARCH" ;;
  *) echo "unknown arch: $ARCH (want amd64|arm64)" >&2; exit 2 ;;
esac

IMAGE="golang:${GO_VERSION}"
LOG="$EVID/repro-double-build-$ARCH.log"

sha256() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$@"; else shasum -a 256 "$@"; fi; }

{
  echo "== reproducibility double-build $ARCH =="
  echo "image=$IMAGE"
  docker image inspect --format 'image_digest={{index .RepoDigests 0}}' "$IMAGE" 2>/dev/null || true
  echo "host=$(uname -srm) docker=$(docker version --format '{{.Server.Version}}')"
  echo "repo_head=$(git rev-parse HEAD)"
  echo "config_sha256=$(sha256 packaging/goreleaser/goreleaser.yaml | awk '{print $1}')"
  echo "cmd=make release-snapshot (x2, same tree, same container)"
} | tee "$LOG"

# shellcheck disable=SC2086  # $PLATFORM must word-split into two argv entries.
docker run --rm $PLATFORM \
  -v "$PWD:/src:ro" \
  -v "amux-gomod-release-$ARCH:/go/pkg/mod" \
  -v "amux-gobuild-release-$ARCH:/root/.cache/go-build" \
  -e GOFLAGS=-buildvcs=false \
  "$IMAGE" bash -c '
    set -euo pipefail
    echo "container: $(uname -srm) $(. /etc/os-release && echo "$PRETTY_NAME")"
    cp -a /src /work && rm -rf /work/.tools /work/dist /work/build /work/.amux-artifacts
    cd /work && git config --global --add safe.directory /work
    . scripts/tools.env && export GOTOOLCHAIN CGO_ENABLED
    install -d -m 700 /reltmp && export TMPDIR=/reltmp
    export GOBIN=/reltools/bin PATH=/reltools/bin:$PATH
    mkdir -p "$GOBIN"
    go install "github.com/goreleaser/goreleaser/v2@$GORELEASER_VERSION" >/dev/null 2>&1
    go install "github.com/anchore/syft/cmd/syft@$SYFT_VERSION"          >/dev/null 2>&1

    # Artifact digests -> the verdict. Everything else -> context only.
    digests() {
      sha256sum dist/amux_linux_amd64_v1/amux dist/amux_linux_arm64_v8.0/amux \
                dist/amuxd_linux_amd64_v1/amuxd dist/amuxd_linux_arm64_v8.0/amuxd \
                dist/amux_*_linux_*.tar.gz | sed "s#dist/#  #"
    }
    context() {
      # Reported, NOT part of the verdict: CycloneDX documents carry a random
      # serialNumber and a generation timestamp, so they are expected to differ
      # per invocation even for byte-identical inputs. checksums.txt lists them,
      # which is why a verifier must diff the ARCHIVE lines, not the whole file.
      echo "  SBOM digests (reported; see docs/release/artifact-verification.md):"
      sha256sum dist/*.sbom.cdx.json | sed "s#dist/#    #"
      echo "  staged completion mtimes (host-side, expected to differ):"
      stat -c "    %n mtime=%Y" build/completions/* 2>/dev/null || true
      echo "  tar member mtimes (amd64):"
      tar -tvzf dist/amux_*_linux_amd64.tar.gz | awk "{print \"   \", \$4, \$5, \$6}"
    }

    echo "== pass 1 =="; make release-snapshot >/dev/null 2>&1
    digests > /d1.txt; cat /d1.txt; context
    sleep 3   # force wall-clock movement between builds
    echo "== pass 2 =="; make release-snapshot >/dev/null 2>&1
    digests > /d2.txt; cat /d2.txt; context

    echo "== VERDICT (artifact digests only) =="
    if diff -u /d1.txt /d2.txt; then
      echo "REPRO: PASS — all binaries and archives byte-identical across two builds"
    else
      echo "REPRO: FAIL — artifact digests diverged across two builds of one commit"
      exit 1
    fi
  ' 2>&1 | tee -a "$LOG"
rc=${PIPESTATUS[0]}
echo "exit=$rc" | tee -a "$LOG"
exit "$rc"
